// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJrT_bbsD_Mko4OT73APwxNbf-anU7IC4',
    appId: '1:408482196731:web:81f682fb8c047b8276545e',
    messagingSenderId: '408482196731',
    projectId: 'adhtp-general-analysis',
    authDomain: 'adhtp-general-analysis.firebaseapp.com',
    storageBucket: 'adhtp-general-analysis.firebasestorage.app',
    measurementId: 'G-LM4EXJ1RVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIPapbCrI2eDlaDv9L3ddE_PDptDPoeJc',
    appId: '1:408482196731:android:050df79279be3f7576545e',
    messagingSenderId: '408482196731',
    projectId: 'adhtp-general-analysis',
    storageBucket: 'adhtp-general-analysis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7xCos9fgn1lSMRNtv61NOl6Oveo_Mojg',
    appId: '1:408482196731:ios:338eb7a9391aefdb76545e',
    messagingSenderId: '408482196731',
    projectId: 'adhtp-general-analysis',
    storageBucket: 'adhtp-general-analysis.firebasestorage.app',
    iosBundleId: 'com.example.adhtpGeneralAnalysis',
  );
}
